# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9736847ed4864e596fd1fa6a4a369d0cfa0baa5faf17aecae801b3fddf19efa8e891f41a9a18e82a77bc67ef35d4e057e5e7e6f0dd3acb77002d6e4338e811bb

test:
  secret_key_base: 9aeb0531f3d54b8c1879636cf55ec9f4b98adc100405c60123e025eddcaf482b8bcebea5a29acbb2c33cb27e46ad0b3c8934cbdd02ef553213610491814c9a95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
